# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: What keeps you up at night?
email: diana.mounter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of answers to the question "What keeps you up at night"
  from designers, developers, and leaders in the tech industry.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://whatkeepsyouupatnight.io" # the base hostname & protocol for your site
twitter_username: broccolini
github_username:  broccolini

# Build settings
markdown: kramdown
